name: 'solarEnergyManagement'
services: 
#banco de dados
  solar_energy_management_db: 
    image: mysql:5.7
    container_name: solar_energy_management_db
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=solar_energy_management
      - MYSQL_USER=solar_energy_management
      - MYSQL_PASSWORD=123456
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    networks:
      solarEnergyManagementNetwork:
        ipv4_address: 180.72.0.2

#aplicação 
  solar_energy_management_app:
    container_name: solar_energy_management_app
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    ports: 
      - "8081:80"
    volumes: 
      - /var/www/storage
      - ./:/var/www  
    env_file: .env
    environment: 
      - "DB_HOST=solar_energy_management_db"
      - "DB_PORT=3306"
    links: 
      - solar_energy_management_db
    depends_on:
      - solar_energy_management_db
    networks:
      solarEnergyManagementNetwork:
        ipv4_address: 180.72.0.3

#servidor web - nginx
  solar_energy_management_nginx:
    container_name: solar_energy_management_nginx
    build: 
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - "8088:80"
    links: 
      - solar_energy_management_app
    volumes: 
      - ./:/var/www
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./nginx/error.log:/var/log/nginx/error.log
    networks:
      solarEnergyManagementNetwork:
        ipv4_address: 180.72.0.4  


networks:
  solarEnergyManagementNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 180.72.0.0/16

volumes: 
  mysql:         